<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../assets/xml/rss.xsl" media="all"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>The Cloistered Monkey (Posts about cuda)</title><link>https://necromuralist.github.io/</link><description></description><atom:link href="https://necromuralist.github.io/categories/cuda.xml" rel="self" type="application/rss+xml"></atom:link><language>en</language><copyright>Contents © 2022 &lt;a href="mailto:cloisteredmonkey.jmark@slmail.me"&gt;Cloistered Monkey&lt;/a&gt; </copyright><lastBuildDate>Tue, 01 Nov 2022 02:42:56 GMT</lastBuildDate><generator>Nikola (getnikola.com)</generator><docs>http://blogs.law.harvard.edu/tech/rss</docs><item><title>PyTorch and the Unknown CUDA Error</title><link>https://necromuralist.github.io/posts/pytorch-and-the-unknown-cuda-error/</link><dc:creator>Cloistered Monkey</dc:creator><description>&lt;div id="table-of-contents"&gt;
&lt;h2&gt;Table of Contents&lt;/h2&gt;
&lt;div id="text-table-of-contents"&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="https://necromuralist.github.io/posts/pytorch-and-the-unknown-cuda-error/#org0edd95b"&gt;The Problem&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="https://necromuralist.github.io/posts/pytorch-and-the-unknown-cuda-error/#org3ff7dfd"&gt;The Symptom&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="https://necromuralist.github.io/posts/pytorch-and-the-unknown-cuda-error/#org56848d2"&gt;The Disease and Its Cure&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div id="outline-container-org0edd95b" class="outline-2"&gt;
&lt;h2 id="org0edd95b"&gt;The Problem&lt;/h2&gt;
&lt;div class="outline-text-2" id="text-org0edd95b"&gt;
&lt;p&gt;
I recently decided to get back into using neural networks again and tried to update my docker container to get &lt;a href="https://www.fast.ai/"&gt;fastai&lt;/a&gt; up and running, but couldn't get CUDA working. After a while spent trying different configurations of CUDA, pytorch, pip, conda, and on and on I eventually found out that there's some kind of problem with using CUDA after suspending and then resuming your system (at least with linux/Ubuntu). This is a documentation of that particular problem and it's fixes (fastest but not necessarily the best answer: always shutdown or reboot the machine, don't suspend and resume).
&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;


&lt;div id="outline-container-org3ff7dfd" class="outline-2"&gt;
&lt;h2 id="org3ff7dfd"&gt;The Symptom&lt;/h2&gt;
&lt;div class="outline-text-2" id="text-org3ff7dfd"&gt;
&lt;p&gt;
This is what happens if I try to use CUDA after waking the machine from a suspend.
&lt;/p&gt;

&lt;div class="highlight"&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;span class="kn"&gt;import&lt;/span&gt; &lt;span class="nn"&gt;torch&lt;/span&gt;

&lt;span class="n"&gt;torch&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;cuda&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;is_available&lt;/span&gt;&lt;span class="p"&gt;()&lt;/span&gt;
&lt;/pre&gt;&lt;/div&gt;

&lt;pre class="example"&gt;
/home/athena/.conda/envs/neurotic-fastai/lib/python3.9/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1666642975993/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() &amp;gt; 0
&lt;/pre&gt;


&lt;p&gt;
As you can see, the error message doesn't really give any useful information about what's wrong - there &lt;i&gt;are&lt;/i&gt; a couple of suggestions but neither seems relevant or at least doesn't lead you to the fix.
&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;

&lt;div id="outline-container-org56848d2" class="outline-2"&gt;
&lt;h2 id="org56848d2"&gt;The Disease and Its Cure&lt;/h2&gt;
&lt;div class="outline-text-2" id="text-org56848d2"&gt;
&lt;p&gt;
There's a post on the &lt;a href="https://discuss.pytorch.org/t/userwarning-cuda-initialization-cuda-unknown-error-this-may-be-due-to-an-incorrectly-set-up-environment-e-g-changing-env-variable-cuda-visible-devices-after-program-start-setting-the-available-devices-to-be-zero/129335/2"&gt;pytorch discussion boards&lt;/a&gt; about this error in which "ptrblck" says that he runs into this problem if his machine is put into the suspend state. While mentioning this he also says that restarting his machine fixes the problem, but restarting it every time seems to defeat the purpose of using suspend (and I'd have to walk to a different room to log in and decrypt the drive after restarting the machine - ugh, so much work). 
&lt;/p&gt;

&lt;p&gt;
Luckily, in a &lt;a href="https://discuss.pytorch.org/t/userwarning-cuda-initialization-cuda-unknown-error-this-may-be-due-to-an-incorrectly-set-up-environment-e-g-changing-env-variable-cuda-visible-devices-after-program-start-setting-the-available-devices-to-be-zero/129335/5"&gt;later post&lt;/a&gt; in the thread the same user mentions that you can also fix it by reloading the &lt;code&gt;nvidia_uvm&lt;/code&gt; kernel module by entering these commands in the terminal:
&lt;/p&gt;

&lt;div class="highlight"&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
&lt;/pre&gt;&lt;/div&gt;

&lt;p&gt;
Which seems to fix the problem for me right at the moment, without the need to restart the machine.
&lt;/p&gt;

&lt;div class="highlight"&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;span class="nb"&gt;print&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;torch&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;cuda&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;is_available&lt;/span&gt;&lt;span class="p"&gt;())&lt;/span&gt;
&lt;/pre&gt;&lt;/div&gt;

&lt;pre class="example"&gt;
False
&lt;/pre&gt;


&lt;p&gt;
Ummm… oops. Well, it did sort of fix one problem - the &lt;code&gt;CUDA unknown error&lt;/code&gt;, but now it's saying that CUDA isn't available on this machine. Every fix begets a new problem. Let's try it again after restarting the Jupyter kernel.
&lt;/p&gt;

&lt;div class="highlight"&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;span class="kn"&gt;import&lt;/span&gt; &lt;span class="nn"&gt;torch&lt;/span&gt;
&lt;span class="nb"&gt;print&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;torch&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;cuda&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;is_available&lt;/span&gt;&lt;span class="p"&gt;())&lt;/span&gt;
&lt;/pre&gt;&lt;/div&gt;

&lt;pre class="example"&gt;
True
&lt;/pre&gt;


&lt;p&gt;
Okay, that's better, I guess. It feels a little inelegant to have to do this, but at least it seems to work.
&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;</description><category>cuda</category><category>pytorch</category><category>troubleshooting</category><guid>https://necromuralist.github.io/posts/pytorch-and-the-unknown-cuda-error/</guid><pubDate>Tue, 01 Nov 2022 00:58:27 GMT</pubDate></item></channel></rss>